# Generated by Django 4.2.3 on 2023-10-18 20:57

from django.db import migrations, models
import news.models.news_model


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(
                validators=[news.models.news_model.validate_date_format]
            ),
        ),
    ]
